create table person(
    id int generated by default as identity primary key,
    full_name varchar(120) not null unique,
    birth_year int not null
);

create table Book(
    id int generated by default as identity primary key,
    name varchar(100) not null,
    author varchar(120),
    year int,
    keeper_id int references person(id) on delete set null,
    taken_at timestamp
);

create table Client(
                     id int generated by default as identity primary key,
                     username varchar(100) not null,
                     password varchar(100) not null,
                     role varchar(100) not null

);

insert into project1.public.person values
        (1, 'Иванов Иван Иванович', 1911),
        (2, 'Петров Петр Петрович', 1992),
        (3, 'Александров Александр Александрович', 2010),
        (4, 'Лебедев Лебедь Лебедевич', 1991),
        (5, 'Книгов Любитель', 2000),
        (6, 'Программов Писатель', 1983),
        (7, 'Программов Читатель', 1983),
        (8, 'Фамильев Имячко Отчествович', 2002),
        (9, 'Ещеодин Человек Человекович', 1999),
        (10, 'Хамдан ибн Мохаммед ибн Рашид Аль Мактум', 1982),
        (11, 'Джо Байден', 1901);


insert into project1.public.book values
        (1, 'Буварь', 'Книгов Любитель', 2020, 11, 2024-02-11 16:37:23),
        (2, 'Как править миром', 'Книгов Любитель', 2019,11,2024-01-13 16:37:23),
        (3, 'Java', 'Шилдт', 2021, 7,2024-06-16 16:37:23),
        (4, 'Война и Мир', 'Лев Толстой', 1840, null),
        (5, 'Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018, null),
        (6, 'Крестныи отец', 'Марио Пьюзо', 1969, null),
        (7, 'Изгоняющии дьявола', 'Уильям Блэтти', 1971, null),
        (8, 'Игра престолов', 'Джордж Р.Р. Мартин', 1996, 1, 2024-02-16 16:37:23),
        (9, 'Гарри Поттер и философский камень', 'Джоан Роулинг', 1997, 2, 2019-12-22 16:37:23),
        (10, 'Гарри Поттер и Дары смерти', 'Джоан Роулинг', 2007, 2, 2023-02-11 16:37:23),
        (11, 'Жена путешественника во времени', 'Одри Ниффенеггер', 2007, 6, 2024-04-22 16:37:23),
        (12, 'Город женщин', 'Элизабет Гилберт', 2019, null),
        (13, 'Невыносимая легкость бытия', 'Милан Кундера', 1984, 3, 2022-03-20 16:37:23),
        (14, 'Челюсти', 'Питер Бенчли', 1974, null);

ALTER SEQUENCE book_id_seq RESTART WITH 15;
ALTER SEQUENCE person_id_seq RESTART WITH 12;